# Logback runtime levels
# Adjust values without editing logback.xml
ROOT_LOG_LEVEL=INFO
APP_CONSOLE_THRESHOLD=INFO

# Framework noise control
SPRING_LOG_LEVEL=OFF
APACHE_LOG_LEVEL=OFF
KAFKA_LOG_LEVEL=OFF

# Hibernate SQL diagnostics
HIBERNATE_SQL_LOG_LEVEL=DEBUG
HIBERNATE_BIND_LOG_LEVEL=TRACE
